# Generated by Django 3.2.4 on 2021-10-12 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(max_length=25)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_network', models.CharField(max_length=15)),
                ('netmask', models.CharField(max_length=15)),
                ('ip_broadcast', models.CharField(max_length=15)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ip_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('hostname', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('os', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipam.os')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipam.subnet')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('protocol', models.CharField(max_length=5)),
                ('port', models.IntegerField()),
                ('domain', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='app/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipam.ip_address')),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=15)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipam.ip_address')),
            ],
        ),
    ]
