# Generated by Django 3.2.4 on 2021-09-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhcp_config',
            name='description',
        ),
        migrations.AddField(
            model_name='application',
            name='domain',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
