# Generated by Django 3.2.4 on 2021-09-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0002_auto_20210921_0201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dhcp_Config',
        ),
        migrations.DeleteModel(
            name='Dhcp_static',
        ),
    ]
