# Generated by Django 3.2.4 on 2021-10-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0002_alter_ip_address_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='username',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
