# Generated by Django 3.2.4 on 2021-09-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0003_auto_20210921_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomain',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='root_domain',
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ip_address',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='SubDomain',
        ),
    ]
