# Generated by Django 3.2.4 on 2021-10-21 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0004_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipam.ip_address'),
        ),
    ]
